version: '3'
services:
  primary:
    image: postgres:13
    container_name: primary
    restart: always
    volumes:
        - ./primary/data:/var/lib/postgresql/data
        - ./primary/postgres.conf:/etc/postgresql/postgresql.conf
        - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
        - ./primary/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "127.0.0.1:15432:5432"
    env_file:
      my_env.env